spring.application.name=vehicle-management-api

# JWT Key
jwt.secret=hNt6O4nHTs/py7dznhUL2/dHasgemxMCwHtjB6FuiYE=

# Script
springdoc.swagger-ui.custom-js=/swagger-custom.js

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Debug SQL
spring.jpa.properties.hibernate.format_sql=true